### PR TITLE
handle upload bugfix:

### LINKED ISSUE #882: After upgrading to 0.1.26 I can't use a handle_upload function from a sub state.
**Describe the bug**
If I try to upload a file from a sub state I get an error.

**To Reproduce**

```
import pynecone as pc
from typing import List

class State(pc.State):
    """The state of the app."""
    pass

class SubState(State):
    img: list[str] = []

    async def handle_upload(self, files: List[pc.UploadFile]):
        """Handle the upload of files.

        Args:
            files: The uploaded file.
        """
        for file in files:
            upload_data = await file.read()
            outfile = f".web/public/{file.filename}"

            # Save the file.
            with open(outfile, "wb") as file_object:
                file_object.write(upload_data)

            # Update the img var.
            self.img.append(file.filename)

def index():
    """The main view."""
    return pc.vstack(

        pc.upload(
            pc.button("Select File"),
            pc.text("Drag and drop files here or click to select files"),
            border="1px dotted black",
            padding="20em",
            multiple=False
        ),
        pc.button(
            "Upload",
            on_click=lambda: SubState.handle_upload(pc.upload_files())
        ),
        pc.foreach(SubState.img, lambda img: pc.image(src=img)),
    )

# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index, title="Upload")
app.compile()

AttributeError: 'State' object has no attribute 'handle_upload'
```

**Expected behavior**
I should be able to upload a file via a sub state without an error.

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.26
 - OS: Ubuntu 23.04
 
**Additional context**
I got the code from here and modified it to use a substate: https://github.com/pynecone-io/pynecone/pull/811 The unmodified code works.

This issue seems similar to this: https://github.com/pynecone-io/pynecone/issues/637

### PR DESCRIPTION
**Pull request by ElijahAhianyo**
This PR adds a fix for the upload handler error when used in a substate.

fixes #882

### CODE REVIEW

**Review by masenf — APPROVED** [review]
😎

**Review by picklelo — APPROVED** [review]
awesome
