### ISSUE TITLE
TypeError: state method missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by sh1nj1** [pynecone-io/pynecone#896]
**Describe the bug**

After upgrading pynecone from 0.1.24 to 0.1.27, TypeError occurs when calling State method
```python
Traceback (most recent call last):
  File "~/service/mini-conda/miniconda3/envs/test/lib/python3.9/site-packages/pynecone/state.py", line 655, in _process_event
    events = fn(**payload)
  File "~/project/github/pynecone_todo/treert/state.py", line 49, in go_signin
    self.clear()
TypeError: clear() missing 1 required positional argument: 'self'
```

**To Reproduce**

State class code:
```python
class State(pc.State):

...

    def clear(self):
        self.account = ""
        self.password = ""
        self.loading = False
        self.logged_in = False
        self.error = ""

    def go_signin(self):
        self.clear()
        return pc.redirect("/signin")
```

Snippet of page code:
```python
pc.button("SignIn", color="primary", on_click=State.go_signin)
```

when I clicked the "SignIn" button, then error occurs.

**Expected behavior**

After upgrading pynecone from 0.1.24 to 0.1.27, everything works without error.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: Python 3.9.16
 - Pynecone Version: 0.1.27
 - OS: Mac OS X 13.2 (22D49)
 - Browser (Optional):
 
**Additional context**
