### ISSUE TITLE
Unable to show img on the page

### ISSUE THREAD

**Issue by johnvonneumann36** [pynecone-io/pynecone#715]
I have put an image under "myProject/assets/img/download.png".
And then I put the following code on this project
`src="/img/download.png"`
After refreshing, the image file does not show up on the page.

![WeChat Image_20230321162040](https://user-images.githubusercontent.com/48921514/226551332-b1f72256-c48e-474b-80cb-97b587f5b558.png)
![WeChat Photo Editor_20230321162136](https://user-images.githubusercontent.com/48921514/226551390-1a8535fb-b278-4f71-941d-8915a3182366.jpg)

The project is set up according to the 'getting started' guide.

Environment:
 - Python Version: 3.7.4
 - Pynecone Version: 0.1.18
 - OS: Windows Server 2019
 - Browser (Optional): Chrome

**Comment by ElijahAhianyo** [comment]
Hey @johnvonneumann36 you should update your pynecone version to `v0.1.20`

**Comment by johnvonneumann36** [comment]
Hi, @ElijahAhianyo I have tried to update my pynecone version to `v0.1.20`, but it seems not to support pandas dataframe anymore.

**Comment by ElijahAhianyo** [comment]
> Hi, @ElijahAhianyo I have tried to update my pynecone version to `v0.1.20`, but it seems not to support pandas dataframe anymore.

Pandas dataframes are still supported. Could you describe what issue you face with 0.1.20 and with code example if possible?

**Comment by johnvonneumann36** [comment]
```
from pcconfig import config
import pandas as pd
import pynecone as pc



docs_url = "https://pynecone.io/docs/getting-started/introduction"
filename = f"{config.app_name}/{config.app_name}.py"

class State(pc.State):
    _backend: pd.DataFrame = pd.DataFrame()

    @pc.var
    def get_df_result(self):
        return self._backend

    def submit_click(self):
        d = pd.DataFrame(data={'col1':[1,2], 'col2':[1,2]})
        self._backend = d


def index():
    return pc.box(
        pc.hstack(
            pc.button("Submit", on_click=State.submit_click),
            pc.data_table(
                data=State.get_df_result,
                overflow_x="scroll",
                width="100%",
                pagination=True,
                search=True,
                sort=True,
                font_size="1em",
                resizable=True,
                display='none',
            ),
            spacing="1.5em",
            font_size="1em",
        ),
        width="100%",
        padding_top="5%",
    )

# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

Compared with `v 0.1.18`, running the same code with `v 0.1.20` will throw an AttributeError.
```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "d:\jobs\myapptest\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "d:\jobs\myapptest\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "d:\jobs\myapptest\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "d:\jobs\myapptest\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "d:\jobs\myapptest\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Jobs\MyAppTest\MyAppTest\MyAppTest.py", line 48, in <module>
    app.add_page(index)
  File "d:\jobs\myapptest\lib\site-packages\pynecone\app.py", line 243, in add_page
    component = component if isinstance(component, Component) else component()
  File "D:\Jobs\MyAppTest\MyAppTest\MyAppTest.py", line 37, in index
    display='none',
  File "d:\jobs\myapptest\lib\site-packages\pynecone\components\datadisplay\datatable.py", line 68, in create
    or (isinstance(data, Var) and utils.is_dataframe(data.type_))
  File "d:\jobs\myapptest\lib\site-packages\pynecone\utils.py", line 1274, in is_dataframe
    return value.__name__ == "DataFrame"
AttributeError: '_SpecialForm' object has no attribute '__name__'
```

It seems when a dataframe is passed to create a datatable, and the problem occurred. I suppose this is caused by the version of pandas which pandas dataframe has no attribute '__name__'. My pandas version is `1.3.4`. But it works fine with pynecone `v 0.1.18`.

**Comment by johnvonneumann36** [comment]
I just compared two versions when datatable is created.
In `v 0.1.18`, the condition is `utils.is_dataframe(type(props.get("data")))`
But in `v 0.1.20`, the condition is changed to `utils.is_dataframe(type(data)) or (isinstance(data, Var) and utils.is_dataframe(data.type_))`

**Comment by johnvonneumann36** [comment]
After further study, I found this is caused by variables with single leading underscore. Private variables cannot be determined whether is a dataframe type.

**Comment by ElijahAhianyo** [comment]
variables with leading underscores are [backend vars](https://pynecone.io/docs/state/vars). However, this seems to be a bug with data tables not working properly when Dataframes are used as computed vars. I could raise an issue for this.  A workaround would be to use base state vars instead:
```python
...

class State(pc.State):
    backend: pd.DataFrame = pd.DataFrame()

    ...


def index():
    return pc.box(
        pc.hstack(
            pc.button("Submit", on_click=State.submit_click),
            pc.data_table(
                data=State.backend,
                overflow_x="scroll",
                width="100%",
                pagination=True,
                search=True,
                sort=True,
                font_size="1em",
                resizable=True,
                display='none',
            ),
            spacing="1.5em",
            font_size="1em",
        ),
        width="100%",
        padding_top="5%",
    )
...
```

**Comment by johnvonneumann36** [comment]
Yes, I have amended this problem. Thank you for your support.
